- name: Create folder
  file:
    path: "/etc/spilo/repository"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX
  tags: asbrl-spilo

- name: Create volume
  docker_volume:
    name: 'spilo-vol'
    state: "{{ VOLUME_STATE }}"
    driver_options:
      type: none
      device: '/spilo-vol'
      o: bind
  tags: asbrl-spilo

- name: Create folder for volume
  file:
    path: "/spilo-vol"
    state: directory
    owner: '101'
    group: '103'
    mode: '700'
  tags: asbrl-spilo

- name: copy template
  template:
    src: "patroni.yaml.j2"
    dest: "/etc/spilo/patroni.yaml"
    mode: u+rwX,g+rwX,o=rX
  tags: asbrl-spilo  

- name: Docker run
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "{{IMAGE}}:{{IMAGE_TAG}}"
    pull: "yes"
    recreate: "yes"
    volumes:
    - /spilo-vol:/home/postgres/pgdata/pgroot/data
    - /etc/spilo/patroni.yaml:/run/postgres.yml
    env:
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      SCOPE: "{{SCOPE}}"
      ETCD_URL: "{{ ETCD_URL }}"
      ETCD_USERNAME: "{{ ETCD_USERNAME }}"
      ETCD_PASSWORD: "{{ ETCD_PASSWORD }}"
      PGUSER_STANDBY: "{{ PGUSER_STANDBY }}"
      PGPASSWORD_STANDBY: "{{ PGPASSWORD_STANDBY }}"
      PGPASSWORD_ADMIN: "{{ PGPASSWORD_ADMIN }}"
      PGPASSWORD_SUPERUSER: "{{ PGPASSWORD_SUPERUSER }}"
      PGDATA: "/home/postgres/pgdata/pgroot/data"
      PGPORT: "{{ PGPORT }}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    log_driver: "{{ DOCKER_LOG_DRIVER }}"
    log_options: "{{ DOCKER_LOG_OPTIONS }}"
    ports:
    -  "{{ HOST_PGPORT }}:{{ PGPORT }}"
    -  "{{ LEADER_PGPORT }}:8008"
  tags: asbrl-spilo